name: iatw
channels:
  - nvidia/label/cuda-11.7.1
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cuda-cudart=11.7.99
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - ncurses=6.3
  - openssl=1.1.1q
  - python=3.10.4
  - readline=8.1.2
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
